-- MySQL Script generated by MySQL Workbench
-- 05/11/20 20:45:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`fecha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fecha` (
  `id_fecha` INT NOT NULL,
  `id_entrada` INT NOT NULL,
  `fecha` VARCHAR(45) NULL,
  PRIMARY KEY (`id_fecha`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`entrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`entrada` (
  `id_entrada` INT NOT NULL AUTO_INCREMENT,
  `id_producto` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `costo` FLOAT NULL,
  `precioDolar` FLOAT NULL,
  `costoEnDolar` FLOAT NULL,
  `precioVenta` FLOAT NULL,
  `gana10` FLOAT NULL,
  `gana20` FLOAT NULL,
  PRIMARY KEY (`id_entrada`),
  CONSTRAINT `id_entrada`
    FOREIGN KEY (`id_entrada`)
    REFERENCES `mydb`.`fecha` (`id_fecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
